// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaaxO2J6XV4rs2WJHEtAV2-lx3-Y6PsyA',
    appId: '1:758946233242:web:cab5ac2debd18cc491d823',
    messagingSenderId: '758946233242',
    projectId: 'colorisma-74ea8',
    authDomain: 'colorisma-74ea8.firebaseapp.com',
    storageBucket: 'colorisma-74ea8.firebasestorage.app',
    measurementId: 'G-29M1N1DXG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHqdXHgJ4Wmx-ib9XOVKRlanYAUeuKZ74',
    appId: '1:758946233242:android:cad73e838969ac0b91d823',
    messagingSenderId: '758946233242',
    projectId: 'colorisma-74ea8',
    storageBucket: 'colorisma-74ea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL_CVCjQf2y4mRXuHIJ9-zLgc2sbQyztU',
    appId: '1:758946233242:ios:e12127c5ac94c55391d823',
    messagingSenderId: '758946233242',
    projectId: 'colorisma-74ea8',
    storageBucket: 'colorisma-74ea8.firebasestorage.app',
    iosBundleId: 'com.example.myGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL_CVCjQf2y4mRXuHIJ9-zLgc2sbQyztU',
    appId: '1:758946233242:ios:e12127c5ac94c55391d823',
    messagingSenderId: '758946233242',
    projectId: 'colorisma-74ea8',
    storageBucket: 'colorisma-74ea8.firebasestorage.app',
    iosBundleId: 'com.example.myGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaaxO2J6XV4rs2WJHEtAV2-lx3-Y6PsyA',
    appId: '1:758946233242:web:21c2f0a19fbcf48491d823',
    messagingSenderId: '758946233242',
    projectId: 'colorisma-74ea8',
    authDomain: 'colorisma-74ea8.firebaseapp.com',
    storageBucket: 'colorisma-74ea8.firebasestorage.app',
    measurementId: 'G-W6WJSW0X86',
  );
}
